DROP DATABASE IF EXISTS bacon_db;
CREATE DATABASE bacon_db;
USE bacon_db;

DROP TABLE IF EXISTS itemList;

CREATE TABLE itemList (
	id INT NOT NULL AUTO_INCREMENT,
	item_name VARCHAR(255) NOT NULL,
	sold BOOL DEFAULT false,
	PRIMARY KEY (id)
);