DROP DATABASE IF EXISTS bacon_db;
CREATE DATABASE bacon_db;
USE bacon_db;

DROP TABLE IF EXISTS itemList;
DROP TABLE IF EXISTS userList;
DROP TABLE IF EXISTS transactionList;

CREATE TABLE itemList (
	id INT NOT NULL AUTO_INCREMENT,
	item_name VARCHAR(255) NOT NULL,
	/*seller_id INT NOT NULL,*/
	sold BOOL DEFAULT false,
	PRIMARY KEY (id)
);

CREATE TABLE userList (
	user_id INT NOT NULL AUTO_INCREMENT,
	user_firstname VARCHAR(255) NOT NULL,
	user_lastName VARCHAR(255) NOT NULL,
	user_userName VARCHAR(255) NOT NULL,
	user_password VARCHAR(255) NOT NULL,
	user_balance DECIMAL(12,2) DEFAULT 5.00,
	user_photo VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (user_id)
);

CREATE TABLE transactionList (
	item_id INT NOT NULL,
	item_price DECIMAL(12,2) NOT NULL,
	buyer_id INT NOT NULL,
	seller_id INT NOT NULL,
	dateSold TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);